In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('namesbystate_ranks_counts.csv')

In [3]:
latest_data = data[data['year'] == data['year'].max()]

In [4]:
latest_data = latest_data.sort_values(['state', 'sex', 'rank'])

In [5]:
def top_N_ex_state_names(sex, state, N):
    top_ten_ex = latest_data[
        (latest_data['rank'] < N) &
        (latest_data['sex'] == sex) &
        (latest_data['state'] != state)
    ]
    return set(top_ten_ex['name'])

In [6]:
top_ten_ex_ohio = top_N_ex_state_names('M', 'OH', 10)
top_ten_ex_ohio

{'Anthony',
 'Asher',
 'Beau',
 'Benjamin',
 'Bennett',
 'Brooks',
 'Cameron',
 'Cooper',
 'Daniel',
 'David',
 'Dylan',
 'Elias',
 'Elijah',
 'Ethan',
 'Ezekiel',
 'Ezra',
 'Grayson',
 'Henry',
 'Hudson',
 'Ian',
 'Isaiah',
 'Jack',
 'Jackson',
 'Jacob',
 'James',
 'Jayden',
 'Jeremiah',
 'John',
 'Joseph',
 'Julian',
 'Kai',
 'Levi',
 'Liam',
 'Lincoln',
 'Luca',
 'Lucas',
 'Luke',
 'Mason',
 'Mateo',
 'Matias',
 'Maverick',
 'Michael',
 'Noah',
 'Oliver',
 'Owen',
 'Samuel',
 'Santiago',
 'Sebastian',
 'Theodore',
 'Thiago',
 'Waylon',
 'Wesley',
 'William',
 'Wyatt'}

In [7]:
latest_data[
    (latest_data['state'] == 'OH') &
    (latest_data['sex'] == 'M') &
    ~latest_data['name'].str.fullmatch('|'.join(top_ten_ex_ohio))]

        state sex  year     name  count  rank
4725120    OH   M  2024      Leo    305    19
4725126    OH   M  2024   Carter    296    22
4725146    OH   M  2024    Miles    252    32
4725150    OH   M  2024    Rowan    244    34
4725155    OH   M  2024    Myles    238    36
...       ...  ..   ...      ...    ...   ...
4728000    OH   M  2024   Zacari      5  1288
4728001    OH   M  2024   Zamari      5  1288
4728002    OH   M  2024   Zavien      5  1288
4728003    OH   M  2024  Zealand      5  1288
4728004    OH   M  2024    Zylon      5  1288

[1441 rows x 6 columns]

In [8]:
def top_N_distinctive(sex, state, N):
    return latest_data[
        (latest_data['state'] == state) &
        (latest_data['sex'] == sex) &
        ~latest_data['name'].str.fullmatch('|'.join(top_N_ex_state_names(sex, state, N)))].iloc[:N]

In [9]:
top_N_distinctive('M', 'OH', 10)

        state sex  year       name  count  rank
4725120    OH   M  2024        Leo    305    19
4725126    OH   M  2024     Carter    296    22
4725146    OH   M  2024      Miles    252    32
4725150    OH   M  2024      Rowan    244    34
4725155    OH   M  2024      Myles    238    36
4725158    OH   M  2024      Roman    237    38
4725159    OH   M  2024     Thomas    237    38
4725164    OH   M  2024  Alexander    235    41
4725166    OH   M  2024     Weston    232    42
4725168    OH   M  2024    Charles    226    43

In [10]:
oh_data = latest_data[
    (latest_data['state'] == 'OH') &
    (latest_data['sex'] == 'M')
]
len(oh_data[oh_data['count'] == oh_data['count'].median()])

55

In [11]:
oh_data[oh_data['rank'] < 11]

        state sex  year      name  count  rank
4725084    OH   M  2024    Oliver    617     1
4725086    OH   M  2024      Noah    597     2
4725088    OH   M  2024  Theodore    595     3
4725090    OH   M  2024      Liam    563     4
4725092    OH   M  2024     Henry    509     5
4725094    OH   M  2024     James    421     6
4725096    OH   M  2024    Hudson    415     7
4725098    OH   M  2024    Elijah    377     8
4725099    OH   M  2024     Lucas    377     8
4725102    OH   M  2024   Grayson    373    10